config/routes.rb
require "resque_web"

Rails.application.routes.draw do
	mount ResqueWeb::Engine => "/resque_web"

	get '404', to: 'errors#page_not_found'
	get '500', to: 'errors#something_went_wrong'
	get 'throw_error', to: 'errors#throw_error'

	devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', passwords: 'users/passwords', registrations: 'users/registrations', sessions: 'users/sessions' }
	devise_for :admin_users, path: '/admin', controllers: { passwords: 'admin_users/passwords', sessions: 'admin_users/sessions' }

	root 'home#index'

	# for showing modelers a scaled back modeling project
	resources :modelers, only: [:show, :create] do
		get :annotate, on: :member
		get :download_upload, on: :member
	end

	resources :scanning_projects, except: :index, param: :slug
	resources :modeling_projects, except: :index, param: :slug
	resources :printing_projects, except: :index, param: :slug do
		put :decrement_quantity, on: :member
		put :increment_quantity, on: :member
	end
	resources :projects, param: :slug, only: [:show, :new]
	resources :comments, only: :create
	resources :uploads, only: [:create, :update, :destroy, :show] do
		get :upload_ready, on: :member
		get :download, on: :member
		get :annotate, on: :member
		post :update_annotations, on: :member
		put :clone, on: :member
		post :nexus, on: :member
		post :smoothing, on: :member
	end
	resources :quotes, only: [:create, :update, :show, :new]
	resources :users, only: :update do
		get :enter_name, on: :collection
	end
	resources :orders, only: [:create, :index]

	get :beta_login, to: 'home#beta_login'
	post :beta_login_submit, to: 'home#beta_login_submit'

	get 'dashboard', to: 'dashboard#index'
	post 'search_projects', to: 'dashboard#search_projects'

	get 'terms-and-conditions', to: 'home#terms_and_conditions'
	get 'about-us', to: 'home#about_us'
	get 'faq', to: 'home#faq'
	get 'how-it-works', to: 'home#how_it_works'
	get 'materials', to: 'home#materials'
	get 'material-list', to: 'home#materials'
	get 'style-guide', to: 'style_guide#style_guide'

	get 'cart', to: 'cart#index'
	get 'viewer-from-quote', to: 'quotes#viewer_from_quote'

	namespace :admin do
		root 'dashboard#index'
		get 'dashboard', to: 'dashboard#index'

		resources :admin_users
		resources :users, only: [:index, :show]
		resources :materials, except: :destroy
		resources :workspaces
		resources :scanning_projects, param: :slug
		resources :modeling_projects, param: :slug do
			put :new_modeling_project_version, on: :member
			put :remove_pricing_group, on: :member
		end
		resources :printing_projects, param: :slug
		resources :projects, param: :slug, only: [:index, :show]
		resources :uploads do
			get :printing_prices, on: :member
			get :download, on: :member
			get :annotate, on: :member
			put :clone, on: :member
			post :upload_printing_price_upload, on: :collection
			post :update_annotations, on: :member
		end
		resources :comments
	end
end

app/models/scanning_project.rb
class ScanningProject < ApplicationRecord
	attr_accessor :purge_scanning_images

	after_create :update_identifier
	after_update :update_status, if: Proc.new {|p| p.status != calculate_status}

	belongs_to :user
	belongs_to :workspace, optional: true
	belongs_to :cart, optional: true
	belongs_to :order, optional: true

	has_one_attached :front_image
	validate :front_image_is_image
	has_one_attached :back_image
	validate :back_image_is_image
	has_one_attached :right_image
	validate :right_image_is_image
	has_one_attached :left_image
	validate :left_image_is_image
	has_one_attached :top_image
	validate :top_image_is_image
	has_one_attached :bottom_image
	validate :bottom_image_is_image

	has_one_attached :temp_upload
	validate :temp_upload_is_model

	has_one :upload, as: :projectable, dependent: :destroy
  has_many :comments, as: :projectable, dependent: :destroy

	# Status
	def create_project_complete?
		name.present? && object_size.present?
	end

	def all_images_attached?
		front_image.attached? && back_image.attached? && top_image.attached? && bottom_image.attached? && right_image.attached? && left_image.attached?
	end

	def scanning_details_complete?
		resolution.present? && color.present? && all_images_attached?
	end

	def exact_size_present?
		length.present? && width.present? && height.present?
	end

	def enter_address_complete?
		user.address.present?
	end

	def calculate_status
		if !create_project_complete? || (object_size == "other" && !exact_size_present?)
			"creating project"
		elsif !resolution.present?
			"entering resolution"
		elsif !color.present?
			"entering color"
		elsif !all_images_attached?
			"attaching images"
		elsif !user_reviewed? && object_size == "other"
			"user reviewing"
		elsif !price_override.present? && object_size == "other"
			"womp reviewing"
		elsif !enter_address_complete?
			"entering address"
		elsif !paid?
			"checkout"
		elsif !upload.present?
			"womp scanning"
		else
			"complete"
		end
	end

	def model_at
		10.business_days.after(self.received_at)
	end

	# Configuration
	def display_name
		name.present? ? "#{name} - #{created_at.strftime('%D')}" : created_at.strftime('%D')
	end

	def to_param
		slug
	end

	def total_price
		if price_override.present? || object_size == "other"
			price_override.to_f
		else
			base = 0
			base += resolution_cost(resolution)
			base += color_cost(color)
			return base
		end
	end

	def resolution_cost(resolution_level)
		if resolution_level.nil? || resolution_level == ""
			return 0
		elsif object_size == "one_inch_to_six_inches"
			return 150 if resolution_level == "medium"
			return 300 if resolution_level == "high"
		elsif object_size == "seven_inches_to_twenty_four_inches"
			return 150 if resolution_level == "low"
			return 200 if resolution_level == "medium"
			return 400 if resolution_level == "high"
		elsif object_size == "twenty_five_inches_to_thirty_two_inches"
			return 250 if resolution_level == "low"
			return 300 if resolution_level == "medium"
			return 600 if resolution_level == "high"
		elsif object_size == "thirty_three_inches_to_fifty_six_inches"
			return 300 if resolution_level == "low"
			return 400 if resolution_level == "medium"
			return 800 if resolution_level == "high"
		end
	end

	def color_cost(color_level)
		if color_level.nil? || color_level == ""
			return 0
		elsif color_level == "no_color"
			return 0
		elsif object_size == "one_inch_to_six_inches" || object_size == "seven_inches_to_twenty_four_inches"
			return 100
		elsif object_size == "twenty_five_inches_to_thirty_two_inches" || object_size == "thirty_three_inches_to_fifty_six_inches"
			return 150
		end
	end

	def display_scanning_object_size
		if object_size == "other"
			"other"
		elsif object_size == "one_inch_to_six_inches"
			'1" - 6"'
		elsif object_size == "seven_inches_to_twenty_four_inches"
			'7" - 24"'
		elsif object_size == "twenty_five_inches_to_thirty_two_inches"
			'25" - 32"'
		elsif object_size == "thirty_three_inches_to_fifty_six_inches"
			'33" - 56"'
		end
	end

	# Action Items
	def purge_all_images
		front_image.purge
		right_image.purge
		top_image.purge
		back_image.purge
		left_image.purge
		bottom_image.purge
	end

	def send_emails
		unless cart_id.present? || (upload.present? && upload.released_to_user == false)
			if paid? && womp_received? && upload.present? && tracking_number.present? && carrier.present?
				ScanningProjectMailer.shipped(self).deliver
			elsif paid? && womp_received? && upload.present? && picked_up?
				ScanningProjectMailer.picked_up(self).deliver
			elsif paid? && womp_received? && upload.present?
				ScanningProjectMailer.complete(self).deliver
			elsif paid? && womp_received? && !upload.present?
				ScanningProjectMailer.womp_received(self).deliver
			elsif paid? && !womp_received?
				ScanningProjectMailer.project_created(self).deliver
			elsif user_reviewed? && price_override.present? && object_size == "other"
				ScanningProjectMailer.payment_requested(self).deliver
			elsif user_reviewed? && !price_override.present? && object_size == "other"
				ScanningProjectMailer.womp_review_needed(self).deliver
			end
		end
	end

	def create_upload(user_object)
		if temp_upload.attached?
			self.create_upload!(admin_user_id: user_object.id)
			temp_upload.update_attributes(name: "file", record_type: "Upload", record_id: self.upload.id)
			self.upload.enqueue_calcuations
		end
	end

	def update_status # is called from outside model sometimes so can't be private
		update_attributes(status: calculate_status)
	end

	private
	# Lifecycle Events
	def update_identifier
		if ScanningProject.where.not(id: self.id).present? && !slug.present?
			update_attributes(slug: ScanningProject.where.not(id: self.id).order('slug asc').last.slug.to_i + 1)
		elsif !slug.present?
			update_attributes(slug: "#{100000 + id}")
		end
	end

	# Validations
	def temp_upload_is_model
		if temp_upload.attached?
			if temp_upload.byte_size > 350000000
				temp_upload.purge
				errors.add('file', 'is too large')
			elsif !['.stl', '.obj'].include?(File.extname(temp_upload.filename.to_s))
				temp_upload.purge
				errors.add('file', 'mist be an .stl or .obj file')
			end
		end
	end

	def front_image_is_image
		if front_image.attached?
			if front_image.blob.byte_size > 10000000
				front_image.purge
				errors.add('front image', 'must be smaller than 10mb')
			elsif !front_image.blob.content_type.starts_with?('image/')
				front_image.purge
				errors.add('front image', 'must be an image')
			end
		end
	end

	def right_image_is_image
		if right_image.attached?
			if right_image.blob.byte_size > 10000000
				right_image.purge
				errors.add('right image', 'must be smaller than 10mb')
			elsif !right_image.blob.content_type.starts_with?('image/')
				right_image.purge
				errors.add('right image', 'must be an image')
			end
		end
	end

	def top_image_is_image
		if top_image.attached?
			if top_image.blob.byte_size > 10000000
				top_image.purge
				errors.add('top image', 'must be smaller than 10mb')
			elsif !top_image.blob.content_type.starts_with?('image/')
				top_image.purge
				errors.add('top image', 'must be an image')
			end
		end
	end

	def back_image_is_image
		if back_image.attached?
			if back_image.blob.byte_size > 10000000
				back_image.purge
				errors.add('back image', 'must be smaller than 10mb')
			elsif !back_image.blob.content_type.starts_with?('image/')
				back_image.purge
				errors.add('back image', 'must be an image')
			end
		end
	end

	def left_image_is_image
		if left_image.attached?
			if left_image.blob.byte_size > 10000000
				left_image.purge
				errors.add('left image', 'must be smaller than 10mb')
			elsif !left_image.blob.content_type.starts_with?('image/')
				left_image.purge
				errors.add('left image', 'must be an image')
			end
		end
	end

	def bottom_image_is_image
		if bottom_image.attached?
			if bottom_image.blob.byte_size > 10000000
				bottom_image.purge
				errors.add('bottom image', 'must be smaller than 10mb')
			elsif !bottom_image.blob.content_type.starts_with?('image/')
				bottom_image.purge
				errors.add('bottom image', 'must be an image')
			end
		end
	end
end

app/controllers/admin/scanning_projects_controller.rb
class Admin::ScanningProjectsController < Admin::AdminController
  before_action :set_scanning_project, only: [:show, :edit, :update, :destroy]

  def show
  end

  def update
    if @scanning_project.update_attributes(scanning_project_params)
      @scanning_project.create_upload(current_admin_user) # this has to go before emails
      @scanning_project.send_emails unless scanning_project_params[:workspace_id].present? # don't send emails if we're only updating the workspace

      redirect_to admin_scanning_project_path(@scanning_project)
    else
      flash[:alert] = @scanning_project.errors.full_messages.to_sentence.downcase
      redirect_back fallback_location: admin_scanning_project_path(@scanning_project)
    end
  end

  private
  def set_scanning_project
    @scanning_project = ScanningProject.find_by(slug: params[:slug]) || ScanningProject.find(params[:slug])
  end

  def scanning_project_params
    params.require(:scanning_project).permit(
      :workspace_id,
      :price_override,
      :womp_received,
      :received_at,
      :temp_upload,
      :tracking_number,
      :carrier,
      :picked_up
    )
  end
end

app/controllers/scanning_projects_controller.rb
class ScanningProjectsController < ApplicationController
	before_action :set_scanning_project, only: [:show, :edit, :update, :destroy]

	def create
		@scanning_project = ScanningProject.new(scanning_project_params)

		if @scanning_project.save
			redirect_to scanning_project_path(@scanning_project)
		else
			redirect_to new_project_path, alert: 'something went wrong'
		end
	end

	def update
		if !params[:scanning_project].present?
			# only time this wouldn't be present is during attach images submit
			redirect_to(@scanning_project, alert: 'you must attach all images')
		elsif @scanning_project.update_attributes(scanning_project_params)
			@scanning_project.update_attributes(name: "scanning ##{@scanning_project.slug}") if !@scanning_project.name.present?
			@scanning_project.purge_all_images if scanning_project_params[:purge_scanning_images].present?
			@scanning_project.send_emails unless scanning_project_params[:cart_id] == ""

			if (scanning_project_params[:cart_id].present? || scanning_project_params[:cart_id] == "") && scanning_project_params.keys.count == 1 # only updating the cart
				redirect_to cart_path
			else
				redirect_to scanning_project_path(@scanning_project)
			end
		else
			flash[:alert] = @scanning_project.errors.full_messages.to_sentence.downcase
			render action: :show
		end
	end

	def destroy
		@scanning_project.destroy
		redirect_to dashboard_path
	end

	def show
		redirect_to scanning_project_path(@scanning_project) if params[:slug].to_i - 100000 < 0
		@scanning_project.comments.update_all(viewed: true)
	end

	def edit
	end

	private
	def set_scanning_project
		@scanning_project = current_user.scanning_projects.find_by(slug: params[:slug]) || current_user.scanning_projects.find(params[:slug])
	end

	def scanning_project_params
		params.require(:scanning_project).permit(
			:user_id,
			:name,
			:object_size,
			:length,
			:width,
			:height,
			:resolution,
			:color,
			:front_image,
			:back_image,
			:right_image,
			:left_image,
			:top_image,
			:bottom_image,
			:user_reviewed,
			:purge_scanning_images,
			:cart_id
		)
	end
end

app/views/admin/scanning_projects/_complete.html.erb
<div class="cf mb4">
  <%= render 'shared/viewer', upload: @scanning_project.upload, project: @scanning_project %>
</div>

<div class="fl w-100">
  <% if (!@scanning_project.tracking_number.present? && !@scanning_project.carrier.present?) && !@scanning_project.picked_up? %>
    <div class="fl w-50 pr2">
      <div class="border-container mb4">
        <h3>potential action</h3>
        <p>you must mark the object as picked up</p>

        <%= form_for @scanning_project, url: admin_scanning_project_path(@scanning_project), method: :put do |f| %>
          <%= f.hidden_field :picked_up, value: true %>

          <fieldset class="mt2">
            <%= f.submit 'mark picked up', class: 'button primary-button fr' %>
          </fieldset>
        <% end %>
      </div>
    </div>

    <div class="fl w-50 pl2">
      <div class="border-container mb4">
        <h3>potential action</h3>
        <p>you must enter the tracking information for the user's object</p>

        <%= form_for @scanning_project, url: admin_scanning_project_path(@scanning_project), method: :put do |f| %>
          <fieldset class="mt2">
            <%= f.label :tracking_number, 'tracking number' %>
            <%= f.text_field :tracking_number %>
          </fieldset>

          <fieldset class="mt2">
            <%= f.label :carrier, 'carrier' %>
            <%= f.text_field :carrier %>
          </fieldset>

          <fieldset class="mt2">
            <%= f.submit 'submit', class: 'button primary-button fr' %>
          </fieldset>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<%= render 'admin/scanning_projects/review_container' %>

<div class="fl w-100 mv4">
  <%= render 'admin/comments/comment_module', project_type: 'ScanningProject', project_id: @scanning_project.id, project: @scanning_project %>
</div>

app/views/admin/scanning_projects/_review_container.html.erb
<div class="cf mb4">
  <div class="fl w-third-l w-100 pa2 tc">
    <% if @scanning_project.object_size == "other" %>
      <p><b>size:</b> <%= @scanning_project.object_size.humanize(capitalize: false) %><br/><span class="i"><%= @scanning_project.length.to_i %>"x<%= @scanning_project.width.to_i %>"x<%= @scanning_project.height.to_i %>"</span></p>
    <% else %>
      <p><b>size:</b> <%= @scanning_project.object_size.humanize(capitalize: false) %></p>
    <% end %>
  </div>

  <div class="fl w-third-l w-100 pa2 tc">
    <p><b>resolution:</b> <%= @scanning_project.resolution %></p>
  </div>

  <div class="fl w-third-l w-100 pa2 tc">
    <p><b>color:</b> <%= @scanning_project.color.humanize(capitalize: false) %></p>
  </div>
</div>

<div class="cf mb4">
  <div class="fl w-third-l w-100 pa2 tc">
    <div class="relative reference-image-wrapper">
      <%= link_to (image_tag @scanning_project.front_image.service_url, class: 'reference-image mb2'), @scanning_project.front_image.service_url, class: 'js-image-modal-link' %>
      <p>front</p>
    </div>
  </div>

  <div class="fl w-third-l w-100 pa2 tc">
    <div class="relative reference-image-wrapper">
      <%= link_to (image_tag @scanning_project.right_image.service_url, class: 'reference-image mb2'), @scanning_project.right_image.service_url, class: 'js-image-modal-link' %>
      <p>right</p>
    </div>
  </div>

  <div class="fl w-third-l w-100 pa2 tc">
    <div class="relative reference-image-wrapper">
      <%= link_to (image_tag @scanning_project.top_image.service_url, class: 'reference-image mb2'), @scanning_project.top_image.service_url, class: 'js-image-modal-link' %>
      <p>top</p>
    </div>
  </div>
</div>

<div class="cf mt4">
  <div class="fl w-third-l w-100 pa2 tc">
    <div class="relative reference-image-wrapper">
      <%= link_to (image_tag @scanning_project.back_image.service_url, class: 'reference-image mb2'), @scanning_project.back_image.service_url, class: 'js-image-modal-link' %>
      <p>back</p>
    </div>
  </div>

  <div class="fl w-third-l w-100 pa2 tc">
    <div class="relative reference-image-wrapper">
      <%= link_to (image_tag @scanning_project.left_image.service_url, class: 'reference-image mb2'), @scanning_project.left_image.service_url, class: 'js-image-modal-link' %>
      <p>left</p>
    </div>
  </div>

  <div class="fl w-third-l w-100 pa2 tc">
    <div class="relative reference-image-wrapper">
      <%= link_to (image_tag @scanning_project.bottom_image.service_url, class: 'reference-image mb2'), @scanning_project.bottom_image.service_url, class: 'js-image-modal-link' %>
      <p>bottom</p>
    </div>
  </div>
</div>

<div class="mv4">
	<p class="measure center tc">user's address on file: <%= @scanning_project.user.address.present? ? @scanning_project.user.address : 'n/a' %></p>
</div>

app/views/admin/scanning_projects/_table.html.erb
<table class="fl w-100 womp-simple-table mb4">
	<thead>
		<tr>
			<th>name</th>
			<th>status</th>
			<th>cost</th>
			<th>created at</th>
			<th>actions</th>
		</tr>
	</thead>

	<tbody>
		<% target.each do |scanning_project| %>
			<tr>
				<td><%= scanning_project.name.present? ? scanning_project.name : 'not named yet' %></td>
				<td><%= scanning_project.status %></td>
				<td><%= scanning_project.total_price.present? ? number_to_currency(scanning_project.total_price) : number_to_currency(0) %></td>
        <td><%= womp_strftime(scanning_project.created_at).downcase %></td>
				<td>
					<%= link_to "view", admin_scanning_project_path(scanning_project) %> - <%= link_to "edit", edit_admin_scanning_project_path(scanning_project) %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/scanning_projects/_womp_reviewing.html.erb
<div class="border-container mb4">
  <h3>required action</h3>
  <p>you must assign a price to this project</p>

  <%= form_for @scanning_project, url: admin_scanning_project_path(@scanning_project), method: :put do |f| %>
    <fieldset class="mt2">
      <%= f.label :price_override, 'price' %>
      <%= f.number_field :price_override, step: :any, placeholder: '--', class: 'mw-100 w-100' %>
    </fieldset>

    <fieldset class="mt2">
      <%= f.submit 'submit', class: 'button primary-button fr' %>
    </fieldset>
  <% end %>
</div>

<%= render 'admin/scanning_projects/review_container' %>

<div class="fl w-100 mv4">
  <%= render 'admin/comments/comment_module', project_type: 'ScanningProject', project_id: @scanning_project.id, project: @scanning_project %>
</div>

app/views/admin/scanning_projects/_womp_scanning.html.erb
<div class="fl w-100">
  <% if !@scanning_project.womp_received? && !@scanning_project.received_at.present? %>
    <div class="border-container mb4">
      <h3>required action</h3>
      <p>you must receive this object in the mail</p>

      <%= form_for @scanning_project, url: admin_scanning_project_path(@scanning_project), method: :put do |f| %>
        <%= f.hidden_field :womp_received, value: true %>
        <%= f.hidden_field :received_at, value: DateTime.now %>

        <fieldset class="mt2">
          <%= f.submit 'mark object received', class: 'button primary-button fr' %>
        </fieldset>
      <% end %>
    </div>
  <% elsif @scanning_project.upload.present? && !@scanning_project.upload.released_to_user? %>
    <div class="cf mv4">
      <%= render 'shared/viewer', upload: @scanning_project.upload, project: @scanning_project %>
    </div>

    <div class="border-container mb4">
      <h3>required action</h3>
      <p>you must verify this model is correct</p>

      <%= form_for @scanning_project.upload, url: admin_upload_path(@scanning_project.upload), method: :put do |f| %>
        <%= f.hidden_field :released_to_user, value: true %>

        <fieldset class="mt2">
          <%= link_to 'model is incorrect - delete', admin_upload_path(@scanning_project.upload), method: :delete, data: { confirm: 'are you sure?' }, class: 'button destructive-button fr' %>
          <%= f.submit 'verify model is correct', class: 'button primary-button fr mr2' %>
        </fieldset>
      <% end %>
    </div>
  <% else %>
    <div class="border-container mb4">
      <h3>required action</h3>
      <p>you must upload a model to this project</p>

      <%= form_for @scanning_project, url: admin_scanning_project_path(@scanning_project), method: :put do |f| %>
        <%= f.hidden_field :admin_user_id, value: current_admin_user.id %>

        <fieldset class="mt2">
          <%= f.file_field :temp_upload, direct_upload: true, multiple: false, class: 'dn' %>
          <%= f.label :temp_upload do %>
            <span class="button secondary-button mr1">choose file</span> <span class="update-text">no file chosen</span>
          <% end %>
        </fieldset>

        <fieldset class="mt2">
          <%= f.submit 'upload', class: 'button primary-button fr' %>
        </fieldset>
      <% end %>
    </div>
  <% end %>
</div>

<%= render 'admin/scanning_projects/review_container' %>

<div class="fl w-100 mv4">
  <%= render 'admin/comments/comment_module', project_type: 'ScanningProject', project_id: @scanning_project.id, project: @scanning_project %>
</div>

app/views/admin/scanning_projects/edit.html.erb
<% breadcrumb :edit_project, @scanning_project %>

<div class="fl w-100 mb4">
  <h1 class="f3 lh-title">edit project - <%= @scanning_project.name.present? ? @scanning_project.name : 'not named yet' %></h1>
</div>

<%= form_for @scanning_project, url: admin_scanning_project_path(@scanning_project) do |f| %>
  <fieldset class="pb2">
    <%= f.label :workspace, 'workspace: ' %>
    <%= f.select :workspace_id, options_from_collection_for_select(Workspace.order(:name), 'id', 'name', f.object.workspace_id), include_blank: true %>
  </fieldset>

  <fieldset class="pb2">
    <%= f.submit 'update project', class: 'button primary-button' %>
  </fieldset>
<% end %>

app/views/admin/scanning_projects/show.html.erb
<% breadcrumb :project, @scanning_project %>

<div class="mb4">
  <h2>3d scanning project</h2>
  <p><%= @scanning_project.display_name %> - #<%= @scanning_project.slug %></p>
  <%= link_to 'edit workspace', edit_admin_scanning_project_path(@scanning_project) %>
</div>

<div class="mb4">
  <h3>basic information</h3>

  <p><b>user:</b> <%= @scanning_project.user.email %></p>
  <p><b>workspace:</b> <%= @scanning_project.workspace.present? ? (link_to @scanning_project.workspace.name, admin_workspace_path(@scanning_project.workspace)) : (link_to 'add workspace', edit_admin_scanning_project_path(@scanning_project)) %></p>
  <p><b>status:</b> <%= @scanning_project.status %></p>
  <p><b>received at:</b> <%= @scanning_project.received_at.present? ? womp_strftime(@scanning_project.received_at) : 'n/a' %></p>
  <p><b>paid at:</b> <%= @scanning_project.paid_at.present? ? womp_strftime(@scanning_project.paid_at) : 'n/a' %></p>
</div>

<% if !@scanning_project.create_project_complete? || (@scanning_project.object_size == "other" && !@scanning_project.exact_size_present?) || !@scanning_project.resolution.present? || !@scanning_project.color.present? || !@scanning_project.all_images_attached? || (!@scanning_project.user_reviewed? && @scanning_project.object_size == "other") %>
  <p>this project is currently being created by the user. check back later for more information.</p>
<% elsif !@scanning_project.price_override.present? && @scanning_project.object_size == "other" %>
  <%= render 'admin/scanning_projects/womp_reviewing' %>
<% elsif !@scanning_project.paid? %>
  <%= render 'admin/scanning_projects/review_container' %>

  <div class="fl w-100 mv4">
    <%= render 'admin/comments/comment_module', project_type: 'ScanningProject', project_id: @scanning_project.id, project: @scanning_project %>
  </div>
<% elsif !@scanning_project.upload.present? || !@scanning_project.upload.released_to_user? %>
  <%= render 'admin/scanning_projects/womp_scanning' %>
<% else %>
  <%= render 'admin/scanning_projects/complete' %>
<% end %>