config/routes.rb
require "resque_web"

Rails.application.routes.draw do
	mount ResqueWeb::Engine => "/resque_web"

	get '404', to: 'errors#page_not_found'
	get '500', to: 'errors#something_went_wrong'
	get 'throw_error', to: 'errors#throw_error'

	devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', passwords: 'users/passwords', registrations: 'users/registrations', sessions: 'users/sessions' }
	devise_for :admin_users, path: '/admin', controllers: { passwords: 'admin_users/passwords', sessions: 'admin_users/sessions' }

	root 'home#index'

	# for showing modelers a scaled back modeling project
	resources :modelers, only: [:show, :create] do
		get :annotate, on: :member
		get :download_upload, on: :member
	end

	resources :scanning_projects, except: :index, param: :slug
	resources :modeling_projects, except: :index, param: :slug
	resources :printing_projects, except: :index, param: :slug do
		put :decrement_quantity, on: :member
		put :increment_quantity, on: :member
	end
	resources :projects, param: :slug, only: [:show, :new]
	resources :comments, only: :create
	resources :uploads, only: [:create, :update, :destroy, :show] do
		get :upload_ready, on: :member
		get :download, on: :member
		get :annotate, on: :member
		post :update_annotations, on: :member
		put :clone, on: :member
		post :nexus, on: :member
		post :smoothing, on: :member
	end
	resources :quotes, only: [:create, :update, :show, :new]
	resources :users, only: :update do
		get :enter_name, on: :collection
	end
	resources :orders, only: [:create, :index]

	get :beta_login, to: 'home#beta_login'
	post :beta_login_submit, to: 'home#beta_login_submit'

	get 'dashboard', to: 'dashboard#index'
	post 'search_projects', to: 'dashboard#search_projects'

	get 'terms-and-conditions', to: 'home#terms_and_conditions'
	get 'about-us', to: 'home#about_us'
	get 'faq', to: 'home#faq'
	get 'how-it-works', to: 'home#how_it_works'
	get 'materials', to: 'home#materials'
	get 'material-list', to: 'home#materials'
	get 'style-guide', to: 'style_guide#style_guide'

	get 'cart', to: 'cart#index'
	get 'viewer-from-quote', to: 'quotes#viewer_from_quote'

	namespace :admin do
		root 'dashboard#index'
		get 'dashboard', to: 'dashboard#index'

		resources :admin_users
		resources :users, only: [:index, :show]
		resources :materials, except: :destroy
		resources :workspaces
		resources :scanning_projects, param: :slug
		resources :modeling_projects, param: :slug do
			put :new_modeling_project_version, on: :member
			put :remove_pricing_group, on: :member
		end
		resources :printing_projects, param: :slug
		resources :projects, param: :slug, only: [:index, :show]
		resources :uploads do
			get :printing_prices, on: :member
			get :download, on: :member
			get :annotate, on: :member
			put :clone, on: :member
			post :upload_printing_price_upload, on: :collection
			post :update_annotations, on: :member
		end
		resources :comments
	end
end

app/views/shared/_alerts.html.erb
<!-- <div class="cf">
	<div class="fr w-100 pa3 ph5-l mt4">
		<% if notice %>
			<p class="tr fr alert-success"><%= notice.downcase.gsub(".", "") %> <span class="notice-exit pointer"><i class="fas fa-times"></i></span></p>
		<% end %>
		<% if alert %>
			<p class="tr fr alert-error"><%= alert.downcase.gsub(".", "") %> <span class="notice-exit pointer"><i class="fas fa-times"></i></span></p>
		<% end %>
	</div>
</div> -->

<% if notice %>
	<div class="toast positive-toast">
		<p><%= notice.downcase.gsub(".", "") %></p>
	</div>
<% end %>

<% if alert %>
	<div class="toast negative-toast">
		<p><%= alert.downcase.gsub(".", "") %></p>
	</div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<ul class="pl0">
			<% object.errors.full_messages.each do |msg| %>
		  	<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-white black">
	<nav class="mw10 center cf pv6 p18">
		<div class="fl w-100 cf ph6 ph0-l pv5 bw1-l b--black-l">
			<div class="fl w-100 w-forth-l tl pv4 pv0-l bb bw1 b--black bn-l">
				<%= image_tag 'womp-avatar.png', class: 'profile-picture profile-picture-comment', style: 'margin-top: -14px' %>
				<%= link_to '© womp 3D inc. 2018 all rights reserved', '#', class: 'db f6 black dim link pb1 pb5-l', style: 'padding-top: 17px; line-height: 2.5' %>
			</div>
			<div class="fl w-100 w-forth-l pv4 pv0-l bb bw1 b--black bn-l">
				<%= link_to 'about us', about_us_path, class: 'db f5 black dim link pb1 pb5-l' %>
				<%= link_to 'contact', 'mailto:info@womp.xyz', class: 'db f5 black dim link pb1 pb5-l' %>
				<%= link_to 'terms & conditions', asset_path('examples.pdf'), class: 'db f5 black dim link', target: "_blank" %>
			</div>
			<div class="fl w-100 w-forth-l pv4 pv0-l bb bw1 b--black bn-l">
				<%= link_to 'how it works', how_it_works_path, class: 'db f5 black dim link pb1 pb5-l' %>
				<%= link_to 'materials', asset_path('materials.pdf'), class: 'db f5 black dim link pb1 pb5-l', target: "_blank" %>
				<%= link_to 'examples', asset_path('examples.pdf'), class: 'db f5 black dim link', target: "_blank" %>
			</div>
			<div class="fl w-100 w-forth-l pv4 pv0-l bb bw1 b--black bn-l">
				<%= link_to 'facebook', 'https://www.facebook.com/wompxyz/', class: 'db f5 black dim link pb1 pb5-l', target: "_blank" %>
				<%= link_to 'twitter', 'javascript:alert("Coming soon!")', class: 'db f5 black dim link pb1 pb5-l' %>
				<%= link_to 'instagram', 'https://www.instagram.com/womp.xyz/', class: 'db f5 black dim link', target: "_blank" %>
				<%= image_tag 'up-arrow.png', class: 'up-arrow' %>
			</div>
		</div>
	</nav>
</footer>

app/views/shared/_header.html.erb
<!-- Start Header on Desktop -->
<header class="dn header-flex bg-white minw-6375 flex-column">
	<div class="f7 tc pt625 pb625 bb-header">
		<span>free shipping on orders over $250</span>
	</div>
	<div class="tc pt625">
		<%= link_to image_tag("logo.png", height: 18, class: 'v-btm', alt: 'womp logo'), root_path, class: 'dib v-btm black f6 pr5' %>
	</div>
	<div class="flex justify-center-ns pt5625 pt1375">
		<div class="pl9375-ns justify-center-ns flex flex-09">
			<%= link_to "how it works", how_it_works_path, class: 'dib v-btm black f6 pr4' %>
			<%= link_to "materials", asset_path('materials.pdf'), class: 'dib v-btm black f6 pr4', target: "_blank" %>
			<%= link_to "examples", '#', class: 'dib v-btm black f6 pr4', target: "_blank" %>
			<%= link_to "blog", '#', class: 'dib v-btm black f6 pr4', target: "_blank" %>
			<%= link_to "pricing quiz", new_quote_path, class: 'dib v-btm black f6 pr4' %>
			<%= link_to "+ start a project", new_project_path, class: 'dib v-btm black f6 pr4' %>
		</div>
		<div class="">
			<% if user_signed_in? %>
				<%= link_to cart_text, cart_path, data: { turbolinks: false }, class: 'pr3 dib v-btm black f6 pr4' %>
				<%= link_to "#{image_tag('icon-comments.svg', class: 'mw-100 w-auto v-mid', style: 'height:20px;', alt: 'comments')}".html_safe, dashboard_path(anchor: 'projects'), class: 'pr3 dib v-btm black f6 pr4' %>
				<%= link_to "#{image_tag('icon-dashboard.svg', class: 'mw-100 w-auto v-mid', style: 'height:20px;', alt: 'dashboard')}".html_safe, dashboard_path(anchor: 'projects'), class: 'pr3 dib v-btm black f6 pr4' %>

				<% if current_user.profile_picture.attached? %>
					<%= link_to 'javascript:void(0)', class: 'js-toggle-header-dropdown dib v-btm black f6 pr4' do %>
					<%= image_tag current_user.profile_picture, class: 'profile-picture profile-picture-header' %>
					<% end %>
				<% else %>
					<%= link_to "#{image_tag('icon-user.svg', class: 'mw-100 w-auto v-mid', style: 'height: 16px', alt: 'settings')}".html_safe, 'javascript:void(0)', class: 'js-toggle-header-dropdown dib v-btm f6' %>
				<% end %>

				<div class="js-dropdown-content absolute bg-white z-999 shadow-4 dn">
					<div class="carrot w1 h1 absolute bg-white">
					</div>

					<%= link_to "my dashboard", dashboard_path(anchor: 'projects'), class: 'pv3 f6 black' %>
					<%= link_to "orders", orders_path, class: 'pv3 f6 black' %>
					<%= link_to "settings", edit_user_registration_path, class: 'pv3 f6 black' %>
					<%= link_to "logout", destroy_user_session_path, method: :delete, class: 'pv3 f6 black' %>
				</div>
			<% else %>
				<%= link_to "login/signup", new_user_session_path, class: 'dib v-btm f6 black' %>
			<% end %>
		</div>
	</div>
</header>
<!-- End Header on Desktop -->


<!-- Start Header on Mobile -->
<header class="db dn-l w-100 bg-white relative pt3 pb4 ph6 tc header-on-mobile">
	<%= link_to image_tag("logo.png", height: 32, class: 'dib v-mid', alt: 'logo'), root_path %>
	<a href="#" class="js-toggle-hamburger-menu"><s class="bar"></s><s class="bar"></s></a>

	<ul class="tc list pt2 ph0 pb0 ma0">
		<li class="pv2"><%= link_to "how it works", how_it_works_path, class: 'black f6' %></li>
		<li class="pv2"><%= link_to "materials", asset_path('materials.pdf'), class: 'black f6', target: "_blank" %></li>
		<li class="pv2"><%= link_to "examples", '#', class: 'black f6', target: "_blank" %></li>
		<li class="pv2"><%= link_to "blog", '#', class: 'black f6', target: "_blank" %></li>
		<li class="pv2"><%= link_to "pricing quiz", new_quote_path, class: 'black f6' %></li>
		<li class="pv2"><%= link_to "+ start a project", new_project_path, class: 'black f6' %></li>
		<% if user_signed_in? %>
			<li class="pv2"><%= link_to mobile_cart_text, cart_path, data: { turbolinks: false }, class: 'black f6' %></li>
			<li class="pv2"><%= link_to "my dashboard", dashboard_path(anchor: 'projects'), class: 'black f6' %></li>
			<li class="pv2"><%= link_to "orders", orders_path, class: 'black f6' %></li>
			<li class="pv2"><%= link_to "settings", edit_user_registration_path, class: 'black f6' %></li>
			<li class="pt2 pb0"><%= link_to "logout", destroy_user_session_path, method: :delete, class: 'black f6' %></li>
		<% else %>
			<li class="pt2 pb0"><%= link_to "login/signup", new_user_session_path, class: 'black f6' %></li>
		<% end %>
	</ul>
</header>
<!-- End Header on Mobile -->

app/views/shared/_page_hero.html.erb
<div class="bg-near-white ph6 ph7-l pv7 tc tl-l w-100">
  <div class="mw8 center pl7-l pv6">
	  <h1 class="f2 fw7 lh-title mv0 mw8 center"><%= title %></h1>

	  <% if sub_title.present? %>
	    <p class="f4 fw4 lh-copy measure-ns mt2 mb5"><%= sub_title %></p>
	  <% end %>
	</div>
</div>

app/views/shared/_styleguide_alerts.html.erb
<div class="toast positive-toast">
  <p>positive toast, positive toast, positive toast</p>
</div>

<div class="toast negative-toast">
  <p>negative toast, negative toast, negative toast</p>
</div>

app/views/shared/_trio_scanning_modeling_printing.html.erb
<div class="center cf mw8 ph6 pv6 w-100">
  <div class="fl w-third-l w-100 ph3 ph4-l tc">
		<% if current_page?(root_path) %>
			<%= link_to "/how-it-works#scanning", class: 'dib w-100 trio-icon-hover trio-icon-scanning' , data: { turbolinks: false } do %>
				<div class="aspect-ratio aspect-ratio--1x1">
					<div class="aspect-ratio--object contain trio-icon-hover-image">
					</div>
				</div>
				<h2 class="f5 black b--black br0 bt bw1 ph3 pt2 mb1 dib">3d scanning</h2>
				<p class="black f7 measure-narrow center trio-icon-hover-content">i have something i'd like to send in to get 3d scanned, including scans i need modified using 3d modeling</p>
			<% end %>
		<% else %>
			<%= link_to scanning_projects_path(scanning_project: { user_id: current_user.id }), data: { turbolinks: false }, class: 'dib w-100 trio-icon-hover trio-icon-scanning', method: :post do %>
				<div class="aspect-ratio aspect-ratio--1x1">
					<div class="aspect-ratio--object contain trio-icon-hover-image">
					</div>
				</div>
				<h2 class="f5 black b--black br0 bt bw1 ph3 pt2 mb1 dib">3d scanning</h2>
				<p class="black f7 measure-narrow center trio-icon-hover-content">i have something i'd like to send in to get 3d scanned, including scans i need modified using 3d modeling</p>
			<% end %>
		<% end %>
	</div>
  <div class="fl w-third-l w-100 ph3 ph4-l tc">
		<% if current_page?(root_path) %>
			<%= link_to "/how-it-works#modeling", class: 'dib w-100 trio-icon-hover trio-icon-modeling' , data: { turbolinks: false } do %>
				<div class="aspect-ratio aspect-ratio--1x1">
					<div class="aspect-ratio--object contain trio-icon-hover-image">
					</div>
				</div>
				<h2 class="f5 black b--black br0 bt bw1 ph3 pt2 mb1 dib">3d modeling</h2>
				<p class="black f7 measure-narrow center trio-icon-hover-content">i need help making my idea into a 3d model, or modifying a 3d model</p>
			<% end %>
		<% else %>
			<%= link_to modeling_projects_path(modeling_project: { user_id: current_user.id }), data: { turbolinks: false }, class: 'dib w-100 trio-icon-hover trio-icon-modeling', method: :post do %>
				<div class="aspect-ratio aspect-ratio--1x1">
					<div class="aspect-ratio--object contain trio-icon-hover-image">
					</div>
				</div>
				<h2 class="f5 black b--black br0 bt bw1 ph3 pt2 mb1 dib">3d modeling</h2>
				<p class="black f7 measure-narrow center trio-icon-hover-content">i need help making my idea into a 3d model, or modifying a 3d model</p>
			<% end %>
		<% end %>
	</div>
	<div class="fl w-third-l w-100 ph3 ph4-l tc">
		<% if current_page?(root_path) %>
			<%= link_to "/how-it-works#printing", class: 'dib w-100 trio-icon-hover trio-icon-printing' , data: { turbolinks: false } do %>
				<div class="aspect-ratio aspect-ratio--1x1">
					<div class="aspect-ratio--object contain trio-icon-hover-image">
					</div>
				</div>
				<h2 class="f5 black b--black br0 bt bw1 ph3 pt2 mb1 dib">3d printing</h2>
				<p class="black f7 measure-narrow center trio-icon-hover-content">i need help making my 3d model into a physical object</p>
			<% end %>
		<% else %>
			<%= link_to printing_projects_path(printing_project: { user_id: current_user.id }), data: { turbolinks: false }, class: 'dib w-100 trio-icon-hover trio-icon-printing', method: :post do %>
				<div class="aspect-ratio aspect-ratio--1x1">
					<div class="aspect-ratio--object contain trio-icon-hover-image">
					</div>
				</div>
				<h2 class="f5 black b--black br0 bt bw1 ph3 pt2 mb1 dib">3d printing</h2>
				<p class="black f7 measure-narrow center trio-icon-hover-content">i need help making my 3d model into a physical object</p>
			<% end %>
		<% end %>
	</div>
</div>

app/views/shared/_viewer.html.erb
<% if browser.device.mobile? || browser.device.tablet? %>
	<div class="tc mv5">
		<p>please log on via desktop to view your model</p>
	</div>
<% elsif upload.is_viewer_ready? %>
	<div class="js-container viewer-container" id="js-viewer-container" data-link="<%= upload.viewer_link %>" data-upload-id="<%= upload.id %>" data-smoothing="<%= upload.smoothing %>" data-filename="<%= upload.file.blob.filename %>" data-screenshot-type="<%= project.present? && project.model_name == "ModelingProejct" && params[:controller] != 'modelers' ? 'aws' : 'download' %>">
		<div id="viewer-info">
			<div class="datafield">
				<p>Volume: <%= number_with_delimiter(upload.volume.round(2), delimiter: ',') %>mm<sup>3</sup></p>
			</div>
			<div class="datafield">
				<p>Surface Area: <%= number_with_delimiter(upload.surface_area.round(2), delimiter: ',') %>mm<sup>2</sup></p>
			</div>
			<div class="datafield">
				<p>Bounding Box: <%= upload.bounding_box_x.round(2) %>mm x <%= upload.bounding_box_y.round(2) %>mm x <%= upload.bounding_box_z.round(2) %>mm</p>
			</div>
		</div>
		<ul id="mats-info"></ul>
		<div id="print-data">
			<div id="price"></div>
			<div id="cur-mats-info"></div>
		</div>
		<a href="javascript:void(0)" class="viewer-fullscreen js-container-fullscreen tooltip" title="fullscreen"><i class="fas fa-arrows-alt"></i></a>
		<a href="javascript:void(0)" class="viewer-smoothing js-viewer-smoothing tooltip" title="toggle smoothing (may improve model edges)"><i class="fas fa-adjust"></i></a>
		<a href="javascript:void(0)" class="viewer-snapshot js-viewer-snapshot tooltip" title="take screenshot"><i class="fas fa-camera"></i></a>
	</div>
<% else %>
	<div class="tc mv5">
		<h2><i class="fas fa-spinner spin"></i></h2>
		<p>your model is currently processing<br/>please check back in 5-10 minutes to see it here</p>
		<p class="caption mt2">the page will refresh automatically</p>
	</div>

	<% if upload.thirty_minutes_old? %>
		<div class="tc">
			<p>something appears to have gone wrong processing your model</p>
		</div>
	<% end %>

	<div id="js-poll-to-refresh" data-upload-id="<%= upload.id %>"></div>
<% end %>