config/routes.rb
require "resque_web"

Rails.application.routes.draw do
	mount ResqueWeb::Engine => "/resque_web"

	get '404', to: 'errors#page_not_found'
	get '500', to: 'errors#something_went_wrong'
	get 'throw_error', to: 'errors#throw_error'

	devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', passwords: 'users/passwords', registrations: 'users/registrations', sessions: 'users/sessions' }
	devise_for :admin_users, path: '/admin', controllers: { passwords: 'admin_users/passwords', sessions: 'admin_users/sessions' }

	root 'home#index'

	# for showing modelers a scaled back modeling project
	resources :modelers, only: [:show, :create] do
		get :annotate, on: :member
		get :download_upload, on: :member
	end

	resources :scanning_projects, except: :index, param: :slug
	resources :modeling_projects, except: :index, param: :slug
	resources :printing_projects, except: :index, param: :slug do
		put :decrement_quantity, on: :member
		put :increment_quantity, on: :member
	end
	resources :projects, param: :slug, only: [:show, :new]
	resources :comments, only: :create
	resources :uploads, only: [:create, :update, :destroy, :show] do
		get :upload_ready, on: :member
		get :download, on: :member
		get :annotate, on: :member
		post :update_annotations, on: :member
		put :clone, on: :member
		post :nexus, on: :member
		post :smoothing, on: :member
	end
	resources :quotes, only: [:create, :update, :show, :new]
	resources :users, only: :update do
		get :enter_name, on: :collection
	end
	resources :orders, only: [:create, :index]

	get :beta_login, to: 'home#beta_login'
	post :beta_login_submit, to: 'home#beta_login_submit'

	get 'dashboard', to: 'dashboard#index'
	post 'search_projects', to: 'dashboard#search_projects'

	get 'terms-and-conditions', to: 'home#terms_and_conditions'
	get 'about-us', to: 'home#about_us'
	get 'faq', to: 'home#faq'
	get 'how-it-works', to: 'home#how_it_works'
	get 'materials', to: 'home#materials'
	get 'material-list', to: 'home#materials'
	get 'style-guide', to: 'style_guide#style_guide'

	get 'cart', to: 'cart#index'
	get 'viewer-from-quote', to: 'quotes#viewer_from_quote'

	namespace :admin do
		root 'dashboard#index'
		get 'dashboard', to: 'dashboard#index'

		resources :admin_users
		resources :users, only: [:index, :show]
		resources :materials, except: :destroy
		resources :workspaces
		resources :scanning_projects, param: :slug
		resources :modeling_projects, param: :slug do
			put :new_modeling_project_version, on: :member
			put :remove_pricing_group, on: :member
		end
		resources :printing_projects, param: :slug
		resources :projects, param: :slug, only: [:index, :show]
		resources :uploads do
			get :printing_prices, on: :member
			get :download, on: :member
			get :annotate, on: :member
			put :clone, on: :member
			post :upload_printing_price_upload, on: :collection
			post :update_annotations, on: :member
		end
		resources :comments
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_action :authenticate_user!
	# skip_before_action :check_if_beta_approved

	def index
	end

	def beta_login
	end

	def beta_login_submit
		if params[:beta_password] && params[:beta_password] == ENV['BETA_PASSWORD']
			cookies[:beta_password] = params[:beta_password]
			redirect_to root_path
		else
			redirect_to beta_login_path, alert: "incorrect password"
		end
	end

	def how_it_works
		@title = "Womp 3D Services - How It Works"
	end

	def materials
		# @title = "Womp 3D Services - Materials"
		# params[:q] = params[:q].present? ? params[:q].reject{|_, v| v.blank?} : nil
		#
		# # There's old links to materials somewhere on the internet with a color_cont filter applied that needs to be removed
		# if params[:q].present? && params[:q][:color_cont].present?
		# 	params[:q].delete(:color_cont)
		# end
		#
		# @q = Material.ransack(params[:q])
		# @materials = @q.result.where.not(archived: true).where.not(name: "name")
		#
		# @colors = Material.where.not(archived: true).where.not(name: "name").colors
		#
		# respond_to do |format|
		# 	format.html
		# 	format.js
		# end
		redirect_to root_path, alert: 'this page has temporarily been removed'
	end

	def terms_and_conditions
		@title = "Womp 3D Services - Terms and Conditions"
	end

	def faq
		@title = "Womp 3D Services - FAQ"
	end

	def about_us
		@title = "Womp 3D Services - About Us"
	end
end

app/views/home/about_us.html.erb
<%= render 'shared/page_hero', title: 'about us', sub_title: nil %>

<div class="fl w-100 pa2 mt4">
	<p class="mb3">womp is a women run digital manufacturing studio based in brooklyn, ny. by opening up the barrier between 3d services and the everyday user, womp’s expert staff provides the necessary tools and guidance for any individual wanting to create their own 3d content. womp’s customer friendly all-in-one web platform helps configure instant quotes for 3d scanning, 3d CAD, and 3d printing with affordable flat rate pricing.</p>
	<p class="mv3">understanding the impact that the 3d file will have on the future of manufacturing and consum- erism, womp takes initiative in providing sustainable options that are beneficial to its users and their environments without jeopardizing the importance of design.</p>
</div>

app/views/home/beta_login.html.erb
<div class="fl w-100 pa2 mv5">
	<%= form_tag({action: 'beta_login_submit'}, { class: 'measure center' }) do %>
		<h3 class="mb2">login</h3>

		<%= text_field_tag :beta_password, nil, { class: 'w-100 mv3', placeholder: 'beta password' } %>
		<p class="mb3">email <a href="mailto:info@womp.xyz">info@womp.xyz</a> for a beta password</p>

		<%= submit_tag "submit", class: 'button primary-button fr' %>
	<% end %>
</div>

app/views/home/index.html.erb
<% content_for :head do %>
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>
<section class="js-slider slider">
	<div class="slide dt js-hero-womp js-scheme-2 hero-womp relative ph6 tc tl-ns w-100 js-scheme-image" style="padding-top: 10rem; padding-bottom: 12rem;">
		<div class="dtc">
			<!-- spacer -->
		</div>
		<div class="db dtc center v-mid black w-100 w-60-m w-45-l relative z-2 js-scheme-text">
			<h1 class="f3 fw7 lh-title mv0" style="font-size: 26px; text-transform: none;">diy 3D Modeling</h1>
			<p class="f6 fw4 lh-copy mt2 mb5 center ml0-ns" style="max-width: 17em; font-size: 14px;">watch your ideas come to life<br class="dn db-l"> with easy and affordable 3d services</p>
			<div class="mv0">
				<%= link_to "START A PROJECT", new_project_path, class: 'button secondary-button mr2 f6', style: 'text-transform: none' %>
			</div>
		</div>
		<div class="dtc">
			<!-- spacer -->
		</div>
	</div>
	<div class="slide active dt js-hero-womp js-scheme-1 hero-womp relative ph6 tc tl-ns w-100 js-scheme-image" style="padding-top: 10rem; padding-bottom: 12rem;">
		<div class="dtc">
			<!-- spacer -->
		</div>
		<div class="db dtc center v-mid white w-100 w-60-m w-45-l relative z-2 js-scheme-text">
			<h1 class="f3 fw7 lh-title mv0" style="font-size: 26px; text-transform: none;">3D scan your world</h1>
			<p class="f6 fw4 lh-copy mt2 mb5 center ml0-ns" style="max-width: 17em; font-size: 14px;">watch your ideas come to life<br class="dn db-l"> with easy and affordable 3d services</p>
			<div class="mv0">
				<%= link_to "START A PROJECT", new_project_path, class: 'button white-button mr2 f6', style: 'text-transform: none' %>
			</div>
		</div>
		<div class="dtc">
			<!-- spacer -->
		</div>
	</div>
	<div class="slide dt js-hero-womp js-scheme-2 hero-womp relative ph6 tc tl-ns w-100 js-scheme-image" style="padding-top: 10rem; padding-bottom: 12rem;">
		<div class="dtc">
			<!-- spacer -->
		</div>
		<div class="db dtc center v-mid black w-100 w-60-m w-45-l relative z-2 js-scheme-text">
			<h1 class="f3 fw7 lh-title mv0" style="font-size: 26px; text-transform: none;">diy 3D Modeling</h1>
			<p class="f6 fw4 lh-copy mt2 mb5 center ml0-ns" style="max-width: 17em; font-size: 14px;">watch your ideas come to life<br class="dn db-l"> with easy and affordable 3d services</p>
			<div class="mv0">
				<%= link_to "START A PROJECT", new_project_path, class: 'button secondary-button mr2 f6', style: 'text-transform: none' %>
			</div>
		</div>
		<div class="dtc">
			<!-- spacer -->
		</div>
	</div>
	<div class="slide dt js-hero-womp js-scheme-1 hero-womp relative ph6 tc tl-ns w-100 js-scheme-image" style="padding-top: 10rem; padding-bottom: 12rem;">
		<div class="dtc">
			<!-- spacer -->
		</div>
		<div class="db dtc center v-mid white w-100 w-60-m w-45-l relative z-2 js-scheme-text">
			<h1 class="f3 fw7 lh-title mv0" style="font-size: 26px; text-transform: none;">3D scan your world</h1>
			<p class="f6 fw4 lh-copy mt2 mb5 center ml0-ns" style="max-width: 17em; font-size: 14px;">watch your ideas come to life<br class="dn db-l"> with easy and affordable 3d services</p>
			<div class="mv0">
				<%= link_to "START A PROJECT", new_project_path, class: 'button white-button mr2 f6', style: 'text-transform: none' %>
			</div>
		</div>
		<div class="dtc">
			<!-- spacer -->
		</div>
	</div>
</section>

<%= render 'shared/trio_scanning_modeling_printing' %>

<section class="bg-near-white br4 center-l dt-l ma2 mw8 ph6 pv6 w-100-l">
	<div class="dtc-l tc v-mid w-100 w-50-l">
		<div class="aspect-ratio aspect-ratio--1x1">
			<%= image_tag 'home_page/front-page-quiz-scheme-1.png', class: "dib mw6 w-100 aspect-ratio--object show-on-scheme-1", alt: 'a collection of 3d models' %>
			<%= image_tag 'home_page/front-page-quiz-scheme-2.png', class: "dib mw6 w-100 aspect-ratio--object show-on-scheme-2", alt: 'an abstract 3d print' %>
		</div>
	</div>

	<div class="dtc-l tc tl-l v-mid w-100 w-50-l">
		<h2 class="f3 fw7 lh-title mv0">need a quick estimate?</h2>
		<p class="f7 fw4 lh-copy measure-narrow-l mt2 mb0">take our quick quiz to find out your projects costs from beginning to end ;)</p>
		<p class="f7 fw4 lh-copy measure-narrow-l mt2 mb7">zero files or experience required!</p>
		<%= link_to "take quiz", new_quote_path, class: "button secondary-button" %>
	</div>
</section>


<section class="center mw7 mv7 ph6 pv7 w-100 tc">
	<h2 class="f3 fw7 lh-title mv6">choose from a wide selection of materials</h2>
	<div class="cf">
		<a href="javascript:void(0)" class="dim fl mb4 tc w-50 w-25-l ph2">
			<div class="aspect-ratio aspect-ratio--3x4 w-100 mb3">
				<%= image_tag 'materials/009.3.png', class: 'aspect-ratio--object show-on-scheme-1 mw-100 w-100 h-auto', alt: 'blush pla material' %>
				<%= image_tag 'materials/014.png', class: 'aspect-ratio--object show-on-scheme-2 mw-100 w-100 h-auto', alt: 'blue pla material' %>
				<span class="absolute bottom-0 db w-100 black b--black bt bw1 pt4 show-on-scheme-1">blush pla</span>
				<span class="absolute bottom-0 db w-100 black b--black bt bw1 pt4 show-on-scheme-2">blue pla</span>
			</div>

		</a>
		<a href="javascript:void(0)" class="dim fl mb4 tc w-50 w-25-l ph2">
			<div class="aspect-ratio aspect-ratio--3x4 w-100 mb3">
				<%= image_tag 'materials/143.png', class: 'aspect-ratio--object show-on-scheme-1 mw-100 w-100 h-auto', alt: 'grey sandstone material' %>
				<%= image_tag 'materials/040.png', class: 'aspect-ratio--object show-on-scheme-2 mw-100 w-100 h-auto', alt: 'frosted resin material' %>
				<span class="absolute bottom-0 db w-100 black b--black bt bw1 pt4 show-on-scheme-1">grey sandstone</span>
				<span class="absolute bottom-0 db w-100 black b--black bt bw1 pt4 show-on-scheme-2">frosted resin</span>
			</div>
		</a>
		<a href="javascript:void(0)" class="dim fl mb4 tc w-50 w-25-l ph2">
			<div class="aspect-ratio aspect-ratio--3x4 w-100 mb3">
				<%= image_tag 'materials/063.png', class: 'aspect-ratio--object show-on-scheme-1 mw-100 w-100 h-auto', alt: 'blue nylon material' %>
				<%= image_tag 'materials/088.png', class: 'aspect-ratio--object show-on-scheme-2 mw-100 w-100 h-auto', alt: 'bronze steel material' %>
				<span class="absolute bottom-0 db w-100 black b--black bt bw1 pt4 show-on-scheme-1">blue nylon</span>
				<span class="absolute bottom-0 db w-100 black b--black bt bw1 pt4 show-on-scheme-2">bronze steel</span>
			</div>
		</a>
		<a href="javascript:void(0)" class="dim fl mb4 tc w-50 w-25-l ph2">
			<div class="aspect-ratio aspect-ratio--3x4 w-100 mb3">
				<%= image_tag 'materials/107.png', class: 'aspect-ratio--object show-on-scheme-1 mw-100 w-100 h-auto', alt: 'polished brass material' %>
				<%= image_tag 'materials/060.png', class: 'aspect-ratio--object show-on-scheme-2 mw-100 w-100 h-auto', alt: 'yellow nylon material' %>
				<span class="absolute bottom-0 db w-100 black b--black bt bw1 pt4 show-on-scheme-1">polished brass</span>
				<span class="absolute bottom-0 db w-100 black b--black bt bw1 pt4 show-on-scheme-2">yellow nylon</span>
			</div>
		</a>
	</div>
	<%#= link_to "see more materials", materials_path, class: 'button mt6 secondary-button' %>
	<%= link_to "SEE MATERIALS", asset_path('materials.pdf'), class: 'button mt6 secondary-button', style: 'text-transform: none', target: "_blank" %>
</section>


<section class="bg-near-white br4 center-l dt-l ma2 mw8 ph6 pv6 w-100-l mv7">
	<div class="dtc-l tc v-mid w-100 w-50-l">
		<div class="dib tc tl-l">
			<h2 class="f3 fw7 lh-title mv0">wondering where to start?</h2>
			<p class="f7 fw4 lh-copy measure-narrow-l mt2 mb0">every project is different</p>
			<p class="f7 fw4 lh-copy measure-narrow-l mt2 mb7">find out more about how to get exactly what you want</p>
			<%= link_to "LEARN MORE", how_it_works_path, class: "button secondary-button", style: 'text-transform: none; float: right' %>
		</div>
	</div>
	<div class="dtc-l tc v-mid w-100 w-50-l">
		<div class="aspect-ratio aspect-ratio--1x1">
			<%= image_tag 'home_page/front-page-how-it-works-scheme-1.png', class: "dib w-100 h-auto aspect-ratio--object show-on-scheme-1", alt: 'a blue 3d printed object' %>
			<%= image_tag 'home_page/front-page-how-it-works-scheme-2.png', class: "dib w-100 h-auto aspect-ratio--object show-on-scheme-2", alt: 'a 3d printed planter' %>
		</div>
	</div>
</section>

<section>
	<h2 class="f3 fw7 lh-title mv6 tc">explore the womp.xyz blog ;)</h2>
	<div class="flexslider">
		<div><div class="item" style="background: blue"></div></div>
		<div><div class="item" style="background: red"></div></div>
		<div><div class="item" style="background: blue"></div></div>
		<div><div class="item" style="background: red"></div></div>
		<div><div class="item" style="background: yellow"></div></div>
		<div><div class="item" style="background: green"></div></div>
	</div>
</section>

<section class="center dt-l mw7 mv7 ph6 pv7 w-100 tc">
	<div class="dtc-l tc v-mid w-100 w-50-l">
		<div class="aspect-ratio aspect-ratio--1x1">
			<%= image_tag 'home_page/front-page-examples-scheme-1.png', class: 'db center mw6 w-100 aspect-ratio--object show-on-scheme-1', alt: 'interlocking 3d printed sandstone rings' %>
			<%= image_tag 'home_page/front-page-examples-scheme-2.png', class: 'db center mw6 w-100 aspect-ratio--object show-on-scheme-2', alt: '3d printed sandstone bowls' %>
		</div>
	</div>
	<div class="dtc-l tc v-mid w-100 w-50-l">
		<div class="dib tc tl-l">
			<h2 class="f3 fw7 lh-title mv0">check out examples</h2>
			<p class="f7 fw4 lh-copy measure-narrow-l mt2 mb7">click below to see our examples pdf</p>
			<%= link_to "TAKE QUIZ", asset_path('examples.pdf'), class: 'button mt6 secondary-button', style: 'text-transform: none', target: "_blank" %>
		</div>
	</div>
</section>

<form class="flex form-promotion">
	<p class="f5 fw4 mb0 promotion-label">stay up to date on our latest product releases + promotions</p>
	<div>
		<input type="text" class="promotion-text" />
		<button type="submit" class="promotion-submit b-ns">SUBMIT</button>
	</div>
</form>

app/views/home/materials.html.erb
<%= render 'shared/page_hero', title: 'materials', sub_title: nil %>


<div class="cf ph2 ph6-ns pv6 w-100 mw8 center">
	<div class="dn db-ns fl-ns mb4 w-20-ns pr3-ns br bw1 b--gray">
		<div id="js-filters-wrapper">
			<%= render 'home/materials/filters_wrapper' %>
		</div>
	</div>
	<div class="fl ph2 pl6-ns pv0 w-100 w-80-ns">
		<%= render 'home/materials/materials_wrapper', materials: @materials %>
	</div>
</div>

app/views/home/materials.js.erb
$('#js-materials-wrapper').html("<%= j render 'home/materials/materials_wrapper', materials: @materials %>");
$('#js-filters-wrapper').html("<%= j render 'home/materials/filters_wrapper' %>");
initializeTabs();
initializeAutoSubmit();

history.pushState(null, null, "<%= request.original_url %>");

app/views/home/terms_and_conditions.html.erb
<%= render 'shared/page_hero', title: 'terms and conditions', sub_title: nil %>

<div class="fl w-100 pa2 mb4">
	<p class="mb2">These following terms and conditions are a legal agreement between you and Womp.</p>
	<p class="mb2">The terms and conditions below apply to your access to and use of www.womp.xyz (the “​<b>platform​</b>” or “<b>​site​</b>”) as well as the production services and features offered by womp through the web platform.</p>
	<p class="mb2">By submitting a project via the web platform, accepting a quote via the platform or otherwise using the site, you agree to be legally bound by all of the terms and conditions of these terms. If you do not agree with these terms and conditions, you should not use womp's site or services.</p>
	<p class="mb2">If you are accepting these terms and conditions on behalf of a company (or other entity) or if you are accessing the services in your capacity as an employee, consultant or agent of a company (or other entity), you represent that you are an employee, consultant or agent of such company (or other entity) and you have the authority to agree, on behalf of such company (or other entity), to all of the terms and conditions of these Terms.</p>

	<h2 class="mt4">service terms</h2>
	<p class="mb2">womp is made up of different services provided through the platform. One of our Services enables you to send in an object to be scanned to create a 3d model. You can also send in instructions, drawings, and/or images for us to create a 3d model. All 3d models are viewable through our 3d viewer on the site and can be printed in our variety of materials offered. Our pricing is based on service and the price for the substance used to 3D scan, 3D Model, or 3D Print.</p>

	<h2 class="mt4">account terms</h2>
	<p class="mb2">You must be 18 years or older to utilize womp's services. In order to use womp's services, you must create an account with womp via the site. By registering you are agreeing to provide all current and accurate identification and information that is requested. womp is not liable for the failure of account security or password. By using our services you are agreeing to not violate these terms and conditions and any laws or regulations. womp has the right to revoke the use of the site and services at any time and does not require a reason. As a user you can delete your account at any time through the site.</p>

	<h2 class="mt4">ordering</h2>
	<ul class="disc">
		<li>placing an order</li>
	</ul>
	<p class="mb2">To order a 3d scan, 3d model, or 3d print through our site you will be asked a series of questions describing the projects, design specifications, dimensions, and material. Next, womp will ask for you to provide shipping instructions. A quote will be generated through the web platform and a representative will be available through the projects messaging system. Depending on your preferred payment method you may be redirected to a third party payment facilitator site. Once the quote is paid the project will be completed and shipped to the provided shipping address.</p>

	<ul class="disc">
		<li>orders that are denied or canceled by womp</li>
	</ul>
	<p class="mb2">womp may reject and cancel your order for technical or other reasons. womp will contact you through the messaging system to inform you of these cancellations and issues and you will receive a full refund.</p>

	<ul class="disc">
		<li>pricing</li>
	</ul>
	<p class="mb2">womp reserves the right to alter prices on the site at any time without any notice. These changes will not alter projects that have already been paid and submitted. If a price is generated incorrectly through our web platform, womp reserves the right to cancel and refund the order. In this case womp will contact and inform the user through the messaging system of these issues. The total quote generated in the invoice includes the fee for material, service, and design. The tax is included in the final invoice and shipping costs are added and determined by the chosen destination of the user. The invoice does not include any import or duty taxes that apply when payment is completed in a currency other than the dollar. In this case your payment company or payment processor may charge you a currency conversion fee. womp is not responsible for these fees nor are these fees known or controlled by womp. You can initiate your payment for your order via credit card. Womp does not begin a project until payment is received.</p>

	<ul class="disc">
		<li>accepted orders</li>
	</ul>
	<p class="mb2">Once your order has been accepted and payment is confirmed, you will be able to to track the progression of your project on the project page on the site. If there are errors within your order or information please contact us immediately through the projects messaging system.</p>

	<ul class="disc">
		<li>shipment</li>
	</ul>
	<p class="mb2">Your completed project will be shipped to the address provided by the user. Dependent upon the shipping address the indicated shipping timeline may change and take longer. All delivery timelines are estimates by womp and can not be 100% guaranteed. womp is not responsible for any loss or damage caused during shipment.</p>

	<ul class="disc">
		<li>cancelled orders</li>
	</ul>
	<p class="mb2">A user can cancel their order, but it must be cancelled within 12 hours after the project has been submitted.</p>

	<h2 class="mt4">warranty; disclaimer.</h2>
	<p class="mb2">womp warrants that projects that are scanned, modeled, or printed by womp will substantially meet the features and descriptions provided by the user within the limitations of 3D technology. The user maintains sole legal responsibility for the design specifications and performance of the 3D model that is the subject of this transaction. please inspect projects upon receival immediately. If the 3d model or print is faulty or has issues when you received it and you believe you are entitled to a replacement or edits in accordance with the warranty above, you must contact womp through the messaging system within 7 business days after receipt of the project. Do not return the 3D print unless we require you to do so. womp reserves the right to determine whether you are entitled to a replacement or refund. womp determines if a refund or replacement is necessary and proves the claims of the user by examining the provided photographs and documentation sent by the user. If womp refunds a project we will take responsibility for any return shipping costs. “Just print it” projects are not eligible for refunds or replacements.</p>

	<p class="mb2">Please note, unless otherwise stated in the description for a specific material, our printing materials are to be used for decorative use only. The user is solely responsible for choosing the best suited material for their project.</p>

	<ul class="disc">
		<li>use of womp's website</li>
	</ul>
	<p class="mb2">All content (excluding user content) including but not limited to, proprietary software, services, text photographs, 3d models are copyright to Womp.</p>

	<ul class="disc">
		<li>user content</li>
	</ul>
	<p class="mb2">User content refers to content uploaded to womp's site by the user. Content includes but is not limited to uploaded 3d models, photographs, drawings, text, and 3d prints. womp has no obligation to review user content and is not responsible for any user content. The user retains all rights to intellectual property of content uploaded to womp's website. Womp will not edit or use any user content other than 3d models that are requested by the user to be modified by womp's services. By using womp's site users are guaranteeing all uploaded content is the original content of the user and not copied from any third party. By uploading your 3D Model to the Services, you grant Shapeways a non-exclusive, royalty free, worldwide, transferable, and sublicensable right and license to use your 3D Model for the manufacturing of your 3D Model in order to fulfill your order.</p>

	<ul class="disc">
		<li>personal information</li>
	</ul>
	<p class="mb2">By using womp's services you agree that womp can collect and use your personal data for what is needed for the project.</p>

	<h2 class="mt4">payments and billing</h2>
	<p class="mb2">any payment terms presented to you in the process of using or signing up for a Paid Service are deemed part of these Terms and Conditions. We use a third-party payment processor (the “Payment Processor”) to bill you through a payment account linked to your Account. The processing of payments will be subject to the terms, conditions and privacy policies of the Payment Processor in addition to these Terms and Conditions. We are not responsible for error by the Payment Processor. By choosing to use Paid Services, you agree to pay us, through the Payment Processor, all charges at the prices then in effect for any use of such Paid Services in accordance with the applicable payment terms and you authorize us, through the Payment Processor, to charge your chosen payment provider (your “Payment Method”). You agree to make payment using that selected Payment Method. The terms of your payment will be based on your Payment Method and may be determined by agreements between you and the financial institution, credit card issuer or other provider of your chosen Payment Method. You must provide current and accurate billing information and must update all information promptly to keep all account information current.</p>

	<h2 class="mt4">legal responsibilities</h2>
	<p class="mb2">Users hold womp, womp's affiliates, vendors, and each of our and their respective employees, contractors, directors, suppliers and representatives from all liabilities, claims, and expenses, including reasonable attorneys’ fees, that arise from or relate to your use or misuse of, or access to, the Services, content, or otherwise from your User Content, 3D Models, violation of these Terms and Conditions, or infringement by you, or any third party using your Account or identity in the Services, of any intellectual property or other right, claim or action, including but not limited to personal injury or property damage of any person or entity. We reserve the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will assist and cooperate with us in asserting any available defenses. This indemnity also includes shop owners who make available models that can be customized by you in the event that a claim is brought against that shop owner for modifications to the model initiated by you.</p>

	<h2 class="mt4">applicable law</h2>
	<p class="mb2">These Terms and Conditions and the use of Services shall be governed by the laws of New York, USA without regard to the conflicts of law principles thereof that would apply the law of any jurisdiction other than New York, USA. You agree that any and all disputes arising from or relating to the subject matter of these Terms and Conditions, including disputes relating to the validity thereof, and any disputes related to the use of the Services, shall be governed by the exclusive jurisdiction and venue of the federal and state courts located in Kings County, New York, USA.</p>

	<h2 class="mt4">changes to these terms and conditions</h2>
	<p class="mb2">womp reserves the right to change these Terms and Conditions at any time and will post any revisions on our site. All transactions are subject to the Terms and Conditions in effect at the time of the transaction.</p>
</div>